# Construct IRIs-as-strings triples
PREFIX edm: <http://www.europeana.eu/schemas/edm/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

CONSTRUCT {
  ?sub edm:isShownBy ?obj .
}
WHERE {
  ?sub edm:isShownBy ?obj .
}
