# Number of items by their class
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT (count(?class) as ?c) ?class WHERE {
  ?sub a ?class .
}
GROUP BY ?class
ORDER BY desc(?c)
