# Convert a textual license indication to an IRI
# Created to work with the NMVW collection
PREFIX edm: <http://www.europeana.eu/schemas/edm/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

CONSTRUCT {
  ?sub edm:rights ?liciri .
}
WHERE {
  ?sub edm:rights ?licstr .
  VALUES (?licstr ?liciri) {
    ("CC-BY-SA 4.0" <http://creativecommons.org/bla>)
    ("(not assigned)" <http://rightsstatements.org/CNE>)
  }
} 
ORDER BY asc(?sub)
 LIMIT 1000
