# Convert image URLs from strings to IRI resources
# See also the SPARQL Update query ../updates/nmvw-iri.rq
PREFIX edm: <http://www.europeana.eu/schemas/edm/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

CONSTRUCT {
  ?sub edm:isShownBy ?iri .
}
WHERE {
  ?sub edm:isShownBy ?obj .
  BIND (IRI(?obj) AS ?iri)
}
