PREFIX dct: <http://purl.org/dc/terms/>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX edm: <http://www.europeana.eu/schemas/edm/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT ?term ?id ?img ?onderwerp ?medium ?lokatie ?spatial ?geonames
WHERE {
  ?term a skos:Concept; skos:narrower+ ?nt ;
  skos:prefLabel ?label .
  ?nt skos:prefLabel ?ntLabel .
  ?item edm:object ?nt; dc:subject/skos:prefLabel ?onderwerp; dct:medium/skos:prefLabel ?medium; dct:spatial ?spatial;
	edm:isShownBy ?img; dc:identifier ?id .
  ?spatial skos:prefLabel ?lokatie; skos:exactMatch ?geonames .
  filter(?label = 'hoeden' || ?ntLabel = 'hoeden')
}
GROUP BY ?item
ORDER BY RAND()
LIMIT 24

