name: CI/CD

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    name: 🎉 Build
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3

    - name: Store artifacts
      uses: actions/upload-artifact@v3
      with:
        name: gui
        path: app

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    environment: staging
    needs: build
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: gui

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.2
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASSWORD }}
        protocol: ftps
        local-dir: ./
        security: strict
