name: CI/CD

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    name: 🎉 Build
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3

    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: app/package-lock.json
      
    - name: 🔨 Build Project
      run: |
        cd app
        npm install
        npm run build

    - name: Store artifacts
      uses: actions/upload-artifact@v3
        with:
          name: gui
          path: app/dist

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    environment: staging
    needs: build
    steps:
    - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: gui

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.2
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASSWORD }}
        protocol: ftps
        local-dir: ./app/dist/
        security: strict
